---
# file: bind/tasks/main.yml
#
# tasks file
#

- import_tasks: debug.yml
  when: debug | default(false)
  tags: debug

- import_tasks: validation.yml
  tags: validation

- import_tasks: installation.yml
  tags: installation
  become: yes

- import_tasks: configuration.yml
  tags: configuration
  become: yes

- import_tasks: apparmor.yml
  tags: apparmor
  become: yes
